Hotfix dev
WildCodeSchool/2023-02-JS-Lille-project-3-groupe1-afac974 pull request #27
Opened 2023-06-23 09:30 UTC by hugocoding21

2023-06-23 09:43 UTC, Sax593 requested changes

2023-06-23 09:43 UTC, Sax593 commented on frontend/src/components/Author/AuthorCard.jsx
> +            {authors.firstname} {authors.lastname}
Where does the author's data come from?

2023-06-23 09:45 UTC, Sax593 submitted a review, later dismissed

2023-06-23 10:02 UTC, hugocoding21 commented on frontend/src/components/Author/AuthorCard.jsx
From the branch "authorpage"

2023-07-04 07:40 UTC, fantinerudent approved these changes

2023-07-10 08:10 UTC, closed without merging